"""added forgien key between user and books

Revision ID: 00327bb94925
Revises: 33e813520e89
Create Date: 2024-04-23 11:09:03.392354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00327bb94925'
down_revision: Union[str, None] = '33e813520e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'added_by')
    # ### end Alembic commands ###
