"""added created by on base model

Revision ID: 228bd187fb34
Revises: d33ca981c28a
Create Date: 2024-04-22 17:14:33.220012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228bd187fb34'
down_revision: Union[str, None] = 'd33ca981c28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint('books_added_by_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    op.drop_column('books', 'added_by_id')
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.add_column('books', sa.Column('added_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_added_by_id_fkey', 'books', 'users', ['added_by_id'], ['id'])
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
