"""added is_active,added_by_admin

Revision ID: 3f7e31e0437b
Revises: 228bd187fb34
Create Date: 2024-04-23 10:10:09.189479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7e31e0437b'
down_revision: Union[str, None] = '228bd187fb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('added_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added_by_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
