"""added columns

Revision ID: 6432dfbcb8d9
Revises: 41161f0f936a
Create Date: 2024-04-22 16:04:38.688324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6432dfbcb8d9'
down_revision: Union[str, None] = '41161f0f936a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated')
    op.drop_column('users', 'created_on')
    op.drop_column('users', 'birth_date')
    op.drop_column('books', 'last_updated')
    op.drop_column('books', 'created_on')
    # ### end Alembic commands ###
