"""soft column delete in user model

Revision ID: b85456145571
Revises: b87b5cd2ad0b
Create Date: 2024-04-23 17:46:01.795021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85456145571'
down_revision: Union[str, None] = 'b87b5cd2ad0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soft_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soft_delete')
    # ### end Alembic commands ###
