"""added extra columns

Revision ID: b87b5cd2ad0b
Revises: b6c477885c9a
Create Date: 2024-04-23 17:14:39.311816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87b5cd2ad0b'
down_revision: Union[str, None] = 'b6c477885c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('books', sa.Column('synopsis', sa.String(), nullable=True))
    op.add_column('books', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_available')
    op.drop_column('books', 'synopsis')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
